#!/bin/sh
# call CPM with .cpm in current $HOME
CYPM=$(dirname $(realpath "$0"))/.local/cypm
"$CYPM" -d REPOSITORY_PATH=$HOME/.cpm/index -d PACKAGE_INSTALL_PATH=$HOME/.cpm/packages -d BIN_INSTALL_PATH=$HOME/.cpm/bin "$@"
